---

- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

- name: "Download node js 14"
  become: yes
  get_url:
    url: https://deb.nodesource.com/setup_14.x
    dest: ~/nodejs.bash

- name: "Excute node bash"
  become: yes
  shell: bash ~/nodejs.bash

- name: "Install nodejs"
  become: yes
  apt:
    name: ["nodejs"]

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes