---

- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes
- name: "Install node js 14"
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

- name: "Install nodejs"
  become: yes
  apt:
    name: ["nodejs", "npm"]

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes