version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-modules
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-modules

  build-backend:
    docker:
      - image: circleci/node13.8.0
    steps:
      - checkout
      - restore_cache:
          key: backend-modules
      - run:
          name: Build backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-modules

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend